#The maid pack that the client player needs to download, needs to fill in the URL and the SHA1 value of the file
#Example: ["https://www.dropbox.com/download/apple.zip", "https://www.dropbox.com/download/cat.zip"]
ClientPackDownloadUrls = []

